//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmsSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        public asset()
        {
            this.ic_ipp_config = new HashSet<ic_ipp_config>();
            this.asset_ipp_port_link = new HashSet<asset_ipp_port_link>();
            this.asset_port_link = new HashSet<asset_port_link>();
        }
    
        public int asset_id { get; set; }
        public int catalog_id { get; set; }
        public int location_id { get; set; }
        public string asset_name { get; set; }
        public string serial_no { get; set; }
        public string ipv4 { get; set; }
        public string ipv6 { get; set; }
        public string install_user_name { get; set; }
        public Nullable<System.DateTime> install_date { get; set; }
        public int user_id { get; set; }
        public byte[] last_updated { get; set; }
        public string remarks { get; set; }
        public string is_layout { get; set; }
        public Nullable<int> pos_x { get; set; }
        public Nullable<int> pos_y { get; set; }
        public System.DateTime last_updated2 { get; set; }
    
        public virtual asset_aux asset_aux { get; set; }
        public virtual ICollection<ic_ipp_config> ic_ipp_config { get; set; }
        public virtual ipp_connect_status ipp_connect_status { get; set; }
        public virtual ICollection<asset_ipp_port_link> asset_ipp_port_link { get; set; }
        public virtual ICollection<asset_port_link> asset_port_link { get; set; }
        public virtual ic_connect_status ic_connect_status { get; set; }
    }
}
