//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmsSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_ipp_port_link
    {
        public int asset_ipp_port_link_id { get; set; }
        public int ipp_asset_id { get; set; }
        public int port_no { get; set; }
        public string alarm_status { get; set; }
        public string wo_status { get; set; }
        public string is_port_trace { get; set; }
        public string ipp_port_status { get; set; }
        public Nullable<int> remote_ic_asset_id { get; set; }
        public Nullable<int> remote_pp_asset_id { get; set; }
        public Nullable<int> remote_port_no { get; set; }
        public byte[] last_updated { get; set; }
    
        public virtual asset asset { get; set; }
    }
}
