//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmsSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_aux
    {
        public int asset_id { get; set; }
        public string as_management_div { get; set; }
        public string as_management_user_name { get; set; }
        public Nullable<System.DateTime> as_free_start_date { get; set; }
        public Nullable<int> as_free_duration { get; set; }
        public Nullable<System.DateTime> as_free_end_date { get; set; }
        public Nullable<System.DateTime> as_start_date { get; set; }
        public Nullable<int> as_duration { get; set; }
        public Nullable<System.DateTime> as_end_date { get; set; }
        public Nullable<int> as_price { get; set; }
        public string as_company { get; set; }
        public string bu_purchase_date { get; set; }
        public string bu_purchase_user_name { get; set; }
        public Nullable<int> bu_depreciation_start_year { get; set; }
        public Nullable<int> bu_depreciation_duration { get; set; }
        public Nullable<int> bu_depreciation_end_year { get; set; }
        public string snmp_get_community { get; set; }
        public string snmp_set_community { get; set; }
        public string snmp_trap_svr_ip { get; set; }
        public string snmp_version { get; set; }
        public string snmp_v3_user { get; set; }
        public string snmp_v3_password { get; set; }
        public Nullable<int> ic_con_id { get; set; }
        public string sv_kind_of_os { get; set; }
        public string sv_os_ver { get; set; }
        public string sv_host_name { get; set; }
        public Nullable<int> sv_num_of_nic { get; set; }
        public Nullable<int> sv_tot_disk_amount { get; set; }
        public Nullable<int> sv_num_of_disks { get; set; }
        public string ra_vcm_type { get; set; }
        public Nullable<int> ra_vcm_depth { get; set; }
        public Nullable<int> st_cur_num_of_disks { get; set; }
        public Nullable<int> st_cur_disk_amount { get; set; }
        public string st_type { get; set; }
        public Nullable<int> sw_max_slots { get; set; }
    
        public virtual asset asset { get; set; }
    }
}
