//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmsSimulator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class i2ms2Entities : DbContext
    {
        public i2ms2Entities()
            : base("name=i2ms2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asset_ipp_port_link> asset_ipp_port_link { get; set; }
        public virtual DbSet<asset_port_link> asset_port_link { get; set; }
        public virtual DbSet<ic_connect_status> ic_connect_status { get; set; }
        public virtual DbSet<ic_ipp_config> ic_ipp_config { get; set; }
        public virtual DbSet<ipp_connect_status> ipp_connect_status { get; set; }
        public virtual DbSet<asset> asset { get; set; }
        public virtual DbSet<asset_aux> asset_aux { get; set; }
    }
}
